package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	graphql1 "github.com/retran/nexus/backend/internal/api/graphql"
	"github.com/retran/nexus/backend/internal/api/graphql/model"
	"github.com/retran/nexus/backend/internal/repository/postgres"
)

// ID is the resolver for the id field.
func (r *auditLogResolver) ID(_ context.Context, obj *postgres.AuditLog) (string, error) {
	return obj.ID.String(), nil
}

// UserID is the resolver for the userId field.
func (r *auditLogResolver) UserID(_ context.Context, obj *postgres.AuditLog) (*string, error) {
	if !obj.UserID.Valid {
		return nil, nil
	}
	var u uuid.UUID
	if err := obj.UserID.Scan(&u); err != nil {
		return nil, fmt.Errorf("scan audit log user id: %w", err)
	}
	s := u.String()
	return &s, nil
}

// User is the resolver for the user field.
func (r *auditLogResolver) User(ctx context.Context, obj *postgres.AuditLog) (*postgres.User, error) {
	if !obj.UserID.Valid {
		return nil, nil
	}
	var u uuid.UUID
	if err := obj.UserID.Scan(&u); err != nil {
		return nil, fmt.Errorf("scan audit log user id: %w", err)
	}
	user, err := r.Query().User(ctx, u.String())
	if err != nil {
		return nil, fmt.Errorf("fetch user: %w", err)
	}
	return user, nil
}

// Metadata is the resolver for the metadata field.
func (r *auditLogResolver) Metadata(_ context.Context, obj *postgres.AuditLog) (*string, error) {
	if obj.Metadata == nil {
		return nil, nil
	}
	s := string(obj.Metadata)
	return &s, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*postgres.User, error) {
	kratosID, err := uuid.Parse(input.KratosIdentityID)
	if err != nil {
		return nil, fmt.Errorf("invalid kratosIdentityId: %w", err)
	}

	params := postgres.CreateUserParams{
		KratosIdentityID: kratosID,
		Email:            input.Email,
		DisplayName:      input.Name,
		Picture:          input.Picture,
		UserRole:         postgres.UserRoleNone,
	}
	if input.Role != nil {
		params.UserRole = *input.Role
	}

	user, err := r.Queries.CreateUser(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("create user: %w", err)
	}
	return &user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*postgres.User, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	params := postgres.UpdateUserParams{
		ID:          userID,
		DisplayName: input.Name,
		Picture:     input.Picture,
	}

	user, err := r.Queries.UpdateUser(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("update user: %w", err)
	}
	return &user, nil
}

// UpdateUserRole is the resolver for the updateUserRole field.
func (r *mutationResolver) UpdateUserRole(ctx context.Context, id string, input model.UpdateUserRoleInput) (*postgres.User, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	params := postgres.UpdateUserRoleParams{
		ID:       userID,
		UserRole: input.Role,
	}

	user, err := r.Queries.UpdateUserRole(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("update user role: %w", err)
	}
	return &user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid user id: %w", err)
	}
	err = r.Queries.DeleteUser(ctx, userID)
	if err != nil {
		return false, fmt.Errorf("delete user: %w", err)
	}
	return true, nil
}

// CreateAuditLog is the resolver for the createAuditLog field.
func (r *mutationResolver) CreateAuditLog(ctx context.Context, input model.CreateAuditLogInput) (*postgres.AuditLog, error) {
	var pgUserID pgtype.UUID
	if input.UserID != nil {
		parsedUserID, err := uuid.Parse(*input.UserID)
		if err != nil {
			return nil, fmt.Errorf("invalid user id: %w", err)
		}
		pgUserID = pgtype.UUID{
			Bytes: parsedUserID,
			Valid: true,
		}
	}

	var metadataBytes []byte
	if input.Metadata != nil {
		metadataBytes = []byte(*input.Metadata)
	}

	log, err := r.Queries.CreateAuditLog(ctx, postgres.CreateAuditLogParams{
		UserID:    pgUserID,
		EventType: input.EventType,
		IpAddress: input.IPAddress,
		UserAgent: input.UserAgent,
		Metadata:  metadataBytes,
	})
	if err != nil {
		return nil, fmt.Errorf("create audit log: %w", err)
	}

	return &log, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*postgres.User, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}
	user, err := r.Queries.GetUser(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("get user: %w", err)
	}
	return &user, nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*postgres.User, error) {
	user, err := r.Queries.GetUserByEmail(ctx, email)
	if err != nil {
		return nil, fmt.Errorf("get user by email: %w", err)
	}
	return &user, nil
}

// UserByKratosID is the resolver for the userByKratosId field.
func (r *queryResolver) UserByKratosID(ctx context.Context, kratosIdentityID string) (*postgres.User, error) {
	kratosID, err := uuid.Parse(kratosIdentityID)
	if err != nil {
		return nil, fmt.Errorf("invalid kratos id: %w", err)
	}
	user, err := r.Queries.GetUserByKratosID(ctx, kratosID)
	if err != nil {
		return nil, fmt.Errorf("get user by kratos id: %w", err)
	}
	return &user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*postgres.User, error) {
	params := postgres.ListUsersParams{
		Limit:  50,
		Offset: 0,
	}
	if limit != nil {
		validatedLimit, err := paginationValue("limit", *limit)
		if err != nil {
			return nil, err
		}
		params.Limit = validatedLimit
	}
	if offset != nil {
		validatedOffset, err := paginationValue("offset", *offset)
		if err != nil {
			return nil, err
		}
		params.Offset = validatedOffset
	}

	users, err := r.Queries.ListUsers(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("list users: %w", err)
	}

	userPtrs := make([]*postgres.User, len(users))
	for i := range users {
		userPtrs[i] = &users[i]
	}
	return userPtrs, nil
}

// UsersByRole is the resolver for the usersByRole field.
func (r *queryResolver) UsersByRole(ctx context.Context, role postgres.UserRole, limit *int, offset *int) ([]*postgres.User, error) {
	params := postgres.ListUsersByRoleParams{
		UserRole: role,
		Limit:    50,
		Offset:   0,
	}
	if limit != nil {
		validatedLimit, err := paginationValue("limit", *limit)
		if err != nil {
			return nil, err
		}
		params.Limit = validatedLimit
	}
	if offset != nil {
		validatedOffset, err := paginationValue("offset", *offset)
		if err != nil {
			return nil, err
		}
		params.Offset = validatedOffset
	}

	users, err := r.Queries.ListUsersByRole(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("list users by role: %w", err)
	}

	userPtrs := make([]*postgres.User, len(users))
	for i := range users {
		userPtrs[i] = &users[i]
	}
	return userPtrs, nil
}

// CountUsers is the resolver for the countUsers field.
func (r *queryResolver) CountUsers(ctx context.Context) (int, error) {
	count, err := r.Queries.CountUsers(ctx)
	if err != nil {
		return 0, fmt.Errorf("count users: %w", err)
	}
	return int(count), nil
}

// CountUsersByRole is the resolver for the countUsersByRole field.
func (r *queryResolver) CountUsersByRole(ctx context.Context, role postgres.UserRole) (int, error) {
	count, err := r.Queries.CountUsersByRole(ctx, role)
	if err != nil {
		return 0, fmt.Errorf("count users by role: %w", err)
	}
	return int(count), nil
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, userID *string, eventType *postgres.AuditEventType, limit *int, offset *int) ([]*postgres.AuditLog, error) {
	var pgUserID pgtype.UUID
	if userID != nil {
		id, err := uuid.Parse(*userID)
		if err != nil {
			return nil, fmt.Errorf("invalid user id: %w", err)
		}
		pgUserID = pgtype.UUID{Bytes: id, Valid: true}
	}

	var eventTypeStr *string
	if eventType != nil {
		s := string(*eventType)
		eventTypeStr = &s
	}

	params := postgres.ListAuditLogsParams{
		UserID:    pgUserID,
		EventType: eventTypeStr,
		Limit:     50,
		Offset:    0,
	}
	if limit != nil {
		validatedLimit, err := paginationValue("limit", *limit)
		if err != nil {
			return nil, err
		}
		params.Limit = validatedLimit
	}
	if offset != nil {
		validatedOffset, err := paginationValue("offset", *offset)
		if err != nil {
			return nil, err
		}
		params.Offset = validatedOffset
	}

	logs, err := r.Queries.ListAuditLogs(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("list audit logs: %w", err)
	}

	logPtrs := make([]*postgres.AuditLog, len(logs))
	for i := range logs {
		logPtrs[i] = &logs[i]
	}
	return logPtrs, nil
}

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, id string) (*postgres.AuditLog, error) {
	logID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid audit log id: %w", err)
	}
	log, err := r.Queries.GetAuditLogByID(ctx, logID)
	if err != nil {
		return nil, fmt.Errorf("get audit log: %w", err)
	}
	return &log, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(_ context.Context, obj *postgres.User) (string, error) {
	return obj.ID.String(), nil
}

// KratosIdentityID is the resolver for the kratosIdentityId field.
func (r *userResolver) KratosIdentityID(_ context.Context, obj *postgres.User) (string, error) {
	return obj.KratosIdentityID.String(), nil
}

// Name is the resolver for the name field.
func (r *userResolver) Name(_ context.Context, obj *postgres.User) (*string, error) {
	return obj.DisplayName, nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(_ context.Context, obj *postgres.User) (postgres.UserRole, error) {
	return obj.UserRole, nil
}

// AuditLog returns graphql1.AuditLogResolver implementation.
func (r *Resolver) AuditLog() graphql1.AuditLogResolver { return &auditLogResolver{r} }

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// User returns graphql1.UserResolver implementation.
func (r *Resolver) User() graphql1.UserResolver { return &userResolver{r} }

type (
	auditLogResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
