# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: APACHE-2.0

version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "build(backend)"
      include: "scope"

  # npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "build(frontend)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      refine:
        patterns:
          - "@refinedev/*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
      tailwindcss:
        patterns:
          - "*tailwind*"
      typescript-eslint:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "eslint*"

  # npm (postgres tooling)
  - package-ecosystem: "npm"
    directory: "/postgres"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "postgres"
    commit-message:
      prefix: "build(postgres)"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build(docker)"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build(docker)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
