# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: Apache-2.0

FROM node:current-alpine3.22

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --network-timeout 100000

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]
