# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: APACHE-2.0

semi: true
singleQuote: true
trailingComma: es5
tabWidth: 2
useTabs: false
printWidth: 80
arrowParens: always
endOfLine: lf
bracketSpacing: true

overrides:
  - files: "*.md"
    options:
      proseWrap: always
      printWidth: 80

  - files: "*.{yml,yaml}"
    options:
      tabWidth: 2
      singleQuote: false

  - files: "*.json"
    options:
      tabWidth: 2
      useTabs: false
