# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: APACHE-2.0

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/nexus ."
  bin = "./tmp/nexus api"
  include_ext = ["go", "tpl", "tmpl", "yaml"]
  exclude_dir = ["tmp", "vendor"]
  log = "air_build.log"

[log]
  time = true

[misc]
  clean_on_exit = true
