# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: APACHE-2.0

FROM golang:1.25-alpine AS development

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.api-server.toml"]
