# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: APACHE-2.0

FROM golang:1.25.3-alpine3.22

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]
