# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: Apache-2.0

FROM golang:1.25.3-alpine

WORKDIR /app

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

# Copy go module files
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source
COPY . .

CMD ["air", "-c", ".air.internal-api.toml"]
