// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/retran/nexus/backend/internal/repository/postgres"
)

type CreateAuditLogInput struct {
	UserID    *string                 `json:"userId,omitempty"`
	EventType postgres.AuditEventType `json:"eventType"`
	IPAddress *string                 `json:"ipAddress,omitempty"`
	UserAgent *string                 `json:"userAgent,omitempty"`
	Metadata  *string                 `json:"metadata,omitempty"`
}

type CreateUserInput struct {
	KratosIdentityID string             `json:"kratosIdentityId"`
	Email            string             `json:"email"`
	Name             *string            `json:"name,omitempty"`
	Picture          *string            `json:"picture,omitempty"`
	Role             *postgres.UserRole `json:"role,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	Name    *string `json:"name,omitempty"`
	Picture *string `json:"picture,omitempty"`
}

type UpdateUserRoleInput struct {
	Role postgres.UserRole `json:"role"`
}
