# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  # VictoriaMetrics - Prometheus-compatible metrics
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  # VictoriaLogs - Log aggregation
  - name: VictoriaLogs
    type: loki
    access: proxy
    url: http://victorialogs:9428
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
      httpMethod: POST

  # VictoriaTraces - Distributed tracing
  - name: VictoriaTraces
    type: tempo
    access: proxy
    url: http://victoriatraces:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: victorialogs
        tags: ["request_id"]
        mappedTags: [{ key: "request_id", value: "request_id" }]
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
      tracesToMetrics:
        datasourceUid: victoriametrics
        tags: [{ key: "service", value: "service" }]
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
      serviceMap:
        datasourceUid: victoriametrics
