# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: Apache-2.0

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://victorialogs:9428/insert/jsonline

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Container name as job
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"

      # Container image
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"

      # Container ID
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"

      # Project name from docker-compose
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_project"]
        target_label: "project"

    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            request_id: request_id
            user_id: user_id
            error: error

      # Extract timestamp
      - timestamp:
          source: time
          format: RFC3339Nano

      # Set log level
      - labels:
          level:
