// Package data implements GraphQL resolvers for the data API service.
// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81
package data

import (
	"context"
	"fmt"

	"github.com/retran/nexus/backend/internal/repository/postgres"
)

// ID is the resolver for the id field.
func (r *auditLogResolver) ID(_ context.Context, _ *postgres.AuditLog) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *auditLogResolver) UserID(_ context.Context, _ *postgres.AuditLog) (*string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// User is the resolver for the user field.
func (r *auditLogResolver) User(_ context.Context, _ *postgres.AuditLog) (*postgres.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Metadata is the resolver for the metadata field.
func (r *auditLogResolver) Metadata(_ context.Context, _ *postgres.AuditLog) (*string, error) {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(_ context.Context, _ CreateUserInput) (*postgres.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(_ context.Context, _ string, _ UpdateUserInput) (*postgres.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(_ context.Context, _ string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// CreateAuditLog is the resolver for the createAuditLog field.
func (r *mutationResolver) CreateAuditLog(_ context.Context, _ CreateAuditLogInput) (*postgres.AuditLog, error) {
	panic(fmt.Errorf("not implemented: CreateAuditLog - createAuditLog"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(_ context.Context, _ string) (*postgres.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(_ context.Context, _ string) (*postgres.User, error) {
	panic(fmt.Errorf("not implemented: UserByEmail - userByEmail"))
}

// UserByKratosID is the resolver for the userByKratosId field.
func (r *queryResolver) UserByKratosID(_ context.Context, _ string) (*postgres.User, error) {
	panic(fmt.Errorf("not implemented: UserByKratosID - userByKratosId"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(_ context.Context, _ *int, _ *int) ([]*postgres.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// CountUsers is the resolver for the countUsers field.
func (r *queryResolver) CountUsers(_ context.Context) (int, error) {
	panic(fmt.Errorf("not implemented: CountUsers - countUsers"))
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(_ context.Context, _ *string, _ *postgres.AuditEventType, _ *int, _ *int) ([]*postgres.AuditLog, error) {
	panic(fmt.Errorf("not implemented: AuditLogs - auditLogs"))
}

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(_ context.Context, _ string) (*postgres.AuditLog, error) {
	panic(fmt.Errorf("not implemented: AuditLog - auditLog"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(_ context.Context, _ *postgres.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// KratosIdentityID is the resolver for the kratosIdentityId field.
func (r *userResolver) KratosIdentityID(_ context.Context, _ *postgres.User) (string, error) {
	panic(fmt.Errorf("not implemented: KratosIdentityID - kratosIdentityId"))
}

// Name is the resolver for the name field.
func (r *userResolver) Name(_ context.Context, _ *postgres.User) (*string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// AuditLog returns AuditLogResolver implementation.
func (r *Resolver) AuditLog() AuditLogResolver { return &auditLogResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type auditLogResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
