# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: Apache-2.0

FROM golang:1.27.1-alpine AS builder

WORKDIR /build

RUN apk add --no-cache git ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags='-w -s -extldflags "-static"' \
    -o /build/bin/worker \
    ./cmd/worker

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo

COPY --from=builder /build/bin/worker /worker

USER 65534:65534

ENTRYPOINT ["/worker"]
