# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: Apache-2.0

FROM golang:1.27.1-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", "tools/.air.system.toml"]
