# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: Apache-2.0

# Grafana Datasource for Tempo
apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        # If you also have Loki, this enables jumping from traces to logs
        datasourceUid: "loki"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags: ["job", "instance", "pod", "namespace"]
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        # Enables jumping from traces to related metrics
        datasourceUid: "mimir"
        tags:
          - key: "service.name"
            value: "service"
      serviceMap:
        datasourceUid: "mimir"
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: "loki"
