# Copyright 2025 Andrew Vasilyev
# SPDX-License-Identifier: APACHE-2.0

plugins:
  - prettier-plugin-sql

parser: sql
language: postgresql
tabWidth: 2
useTabs: false
printWidth: 80

keywordCase: upper
dataTypeCase: upper
functionCase: upper
